#!/usr/bin/env python3
"""Create a Gemini-friendly export of the repository.

The export excludes heavy/binary artifacts and splits large text files into
smaller chunks so they can be imported by tooling that enforces per-file limits.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path

DEFAULT_MAX_CHARS = 18_000

EXCLUDE_DIR_PREFIXES = (
    ".git/",
    "node_modules/",
    "dist/",
    "coverage/",
    "playwright-report/",
    ".playwright/",
)

EXCLUDE_SUFFIXES = {
    ".pth",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".webp",
    ".ico",
    ".icns",
    ".pdf",
    ".zip",
    ".dmg",
    ".appimage",
    ".exe",
    ".dll",
    ".so",
    ".dylib",
}


def run_git_ls_files(repo_root: Path) -> list[str]:
    result = subprocess.run(
        ["git", "ls-files"],
        cwd=repo_root,
        check=True,
        capture_output=True,
        text=True,
    )
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def is_excluded(path: str) -> bool:
    normalized = path.replace("\\", "/")
    if normalized.startswith(EXCLUDE_DIR_PREFIXES):
        return True
    suffix = Path(normalized).suffix.lower()
    return suffix in EXCLUDE_SUFFIXES


def read_utf8(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return None


def split_text(text: str, chunk_size: int) -> list[str]:
    chunks: list[str] = []
    idx = 0
    while idx < len(text):
        end = min(len(text), idx + chunk_size)
        if end < len(text):
            newline_pos = text.rfind("\n", idx, end)
            if newline_pos > idx + int(chunk_size * 0.4):
                end = newline_pos + 1
        chunks.append(text[idx:end])
        idx = end
    return chunks


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def chunk_path(base_path: str, idx: int, total: int) -> str:
    p = Path(base_path)
    stem = p.stem
    suffix = p.suffix
    return str(p.with_name(f"{stem}.part{idx:03d}-of-{total:03d}{suffix}"))


def build_export(repo_root: Path, out_dir: Path, max_chars: int) -> dict:
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    files = run_git_ls_files(repo_root)
    manifest = {
        "max_chars": max_chars,
        "copied": [],
        "split": [],
        "excluded": [],
        "binary": [],
    }

    for rel in files:
        if is_excluded(rel):
            manifest["excluded"].append(rel)
            continue

        src = repo_root / rel
        if not src.is_file():
            continue

        text = read_utf8(src)
        if text is None:
            manifest["binary"].append(rel)
            continue

        if len(text) <= max_chars:
            write_file(out_dir / rel, text)
            manifest["copied"].append(rel)
            continue

        chunks = split_text(text, max_chars)
        chunk_files = []
        for i, chunk in enumerate(chunks, start=1):
            rel_chunk = chunk_path(rel, i, len(chunks))
            write_file(out_dir / rel_chunk, chunk)
            chunk_files.append(rel_chunk)

        manifest["split"].append({"source": rel, "parts": chunk_files})

    readme = (
        "# Gemini Import Bundle\n\n"
        "This folder is generated by `scripts/prepare_gemini_import.py`.\n\n"
        "- Large text files are split into `*.partNNN-of-NNN.*`\n"
        "- Binary/heavy artifacts are excluded\n"
        "- Mapping is stored in `gemini-import-manifest.json`\n"
    )
    write_file(out_dir / "README.md", readme)
    write_file(out_dir / "gemini-import-manifest.json", json.dumps(manifest, indent=2, ensure_ascii=False))
    return manifest


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare Gemini-friendly repository export")
    parser.add_argument("--out", default="gemini-import", help="Output directory (default: gemini-import)")
    parser.add_argument(
        "--max-chars",
        type=int,
        default=DEFAULT_MAX_CHARS,
        help=f"Max chars per text file before splitting (default: {DEFAULT_MAX_CHARS})",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[1]
    out_dir = repo_root / args.out
    manifest = build_export(repo_root, out_dir, args.max_chars)
    print(
        "Prepared Gemini import bundle:",
        f"copied={len(manifest['copied'])}",
        f"split={len(manifest['split'])}",
        f"excluded={len(manifest['excluded'])}",
        f"binary={len(manifest['binary'])}",
        sep="\n  ",
    )


if __name__ == "__main__":
    main()
